name: apach
description: "A new Flutter project."
publish_to: "https://github.com/Hadi719/Apach/releases"
platforms:
  android:

version: 0.0.1+1

# Created with flutter 3.24.1
environment:
  sdk: ^3.5.1

isar_version: &isar_version 3.1.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  logging: ^1.2.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.4
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  isar_generator: *isar_version

flutter:
  uses-material-design: true
